/**
 * @file safety_constants.h
 * @author Addverb Technologies (humanoid@addverb.com)
 * @brief Safety Constants for Reference
 * @version 1.0
 * @date 2023-10-11
 * 
 * @copyright Copyright (c) 2023
 * 
 */


#ifndef SAFETY_CONSTANTS_H_
#define SAFETY_CONSTANTS_H_

////////////////// JOINT POSITION THRESHOLD ///////////

#define SAFETY_BASE_THRESH 5.5

#define SAFETY_J0_THRESHOLD_MIN -0.785
#define SAFETY_J1_THRESHOLD_MIN -1.57
#define SAFETY_J2_THRESHOLD_MIN -3.20
#define SAFETY_J3_THRESHOLD_MIN -0.785
#define SAFETY_J4_THRESHOLD_MIN -1.57
#define SAFETY_J5_THRESHOLD_MIN -3.20
#define SAFETY_J6_THRESHOLD_MIN -0.785
#define SAFETY_J7_THRESHOLD_MIN -1.57
#define SAFETY_J8_THRESHOLD_MIN -3.20
#define SAFETY_J9_THRESHOLD_MIN -0.785
#define SAFETY_J10_THRESHOLD_MIN -1.57
#define SAFETY_J11_THRESHOLD_MIN -3.20

#define SAFETY_J0_THRESHOLD_MAX 0.785
#define SAFETY_J1_THRESHOLD_MAX 3.5
#define SAFETY_J2_THRESHOLD_MAX 0.0
#define SAFETY_J3_THRESHOLD_MAX 0.785
#define SAFETY_J4_THRESHOLD_MAX 3.5
#define SAFETY_J5_THRESHOLD_MAX 0.0
#define SAFETY_J6_THRESHOLD_MAX 0.785
#define SAFETY_J7_THRESHOLD_MAX 3.5
#define SAFETY_J8_THRESHOLD_MAX 0.0
#define SAFETY_J9_THRESHOLD_MAX 0.785
#define SAFETY_J10_THRESHOLD_MAX 3.5
#define SAFETY_J11_THRESHOLD_MAX 0.0

////////////// VELOCITY THRESHOLD //////////////////

#define SAFETY_BASE_VEL_THRESH 40.0

#define SAFETY_VEL_J0_THRESHOLD SAFETY_BASE_VEL_THRESH
#define SAFETY_VEL_J1_THRESHOLD SAFETY_BASE_VEL_THRESH
#define SAFETY_VEL_J2_THRESHOLD SAFETY_BASE_VEL_THRESH
#define SAFETY_VEL_J3_THRESHOLD SAFETY_BASE_VEL_THRESH
#define SAFETY_VEL_J4_THRESHOLD SAFETY_BASE_VEL_THRESH
#define SAFETY_VEL_J5_THRESHOLD SAFETY_BASE_VEL_THRESH
#define SAFETY_VEL_J6_THRESHOLD SAFETY_BASE_VEL_THRESH
#define SAFETY_VEL_J7_THRESHOLD SAFETY_BASE_VEL_THRESH
#define SAFETY_VEL_J8_THRESHOLD SAFETY_BASE_VEL_THRESH
#define SAFETY_VEL_J9_THRESHOLD SAFETY_BASE_VEL_THRESH
#define SAFETY_VEL_J10_THRESHOLD SAFETY_BASE_VEL_THRESH
#define SAFETY_VEL_J11_THRESHOLD SAFETY_BASE_VEL_THRESH


/////////////// TORQUE THRESHOLD ///////////////////

#define SAFETY_BASE_TORQUE_THRESH 50.0
#define SAFETY_BASE_TORQUE_RECOMMENDED 40.0

#define SAFETY_TOR_J0_THRESHOLD SAFETY_BASE_TORQUE_RECOMMENDED
#define SAFETY_TOR_J1_THRESHOLD SAFETY_BASE_TORQUE_RECOMMENDED
#define SAFETY_TOR_J2_THRESHOLD SAFETY_BASE_TORQUE_RECOMMENDED
#define SAFETY_TOR_J3_THRESHOLD SAFETY_BASE_TORQUE_RECOMMENDED
#define SAFETY_TOR_J4_THRESHOLD SAFETY_BASE_TORQUE_RECOMMENDED
#define SAFETY_TOR_J5_THRESHOLD SAFETY_BASE_TORQUE_RECOMMENDED
#define SAFETY_TOR_J6_THRESHOLD SAFETY_BASE_TORQUE_RECOMMENDED
#define SAFETY_TOR_J7_THRESHOLD SAFETY_BASE_TORQUE_RECOMMENDED
#define SAFETY_TOR_J8_THRESHOLD SAFETY_BASE_TORQUE_RECOMMENDED
#define SAFETY_TOR_J9_THRESHOLD SAFETY_BASE_TORQUE_RECOMMENDED
#define SAFETY_TOR_J10_THRESHOLD SAFETY_BASE_TORQUE_RECOMMENDED
#define SAFETY_TOR_J11_THRESHOLD SAFETY_BASE_TORQUE_RECOMMENDED




#endif 
